services:
  go-application:
    build:
      context: ./go-application
    container_name: go-application
    image: go-application
    ports:
      - "4020:5000"
  python-application:
    build:
      context: ./python-application
    container_name: python-application
    image: python-application
    ports:
      - "81:5000"
  dotnet-application:
    build:
      context: ./dotnet-application
    container_name: dotnet-application
    image: dotnet-application
    ports:
      - "82:5000"
  nodejs-application:
    build:
      context: ./nodejs-application
    container_name: nodejs-application
    image: nodejs-application
    ports:
      - "83:5000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_USER: "wp"
      WORDPRESS_DB_PASSWORD: "Wp123*"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_CONFIG_EXTRA: |
        define('PROMETHEUS_KEY','fg98dfgkj');
        define('PROMETHEUS_METRICS_FOR_WP_DISABLE_CACHE', 'true');
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
  mysql:
    image: mysql:5.7
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'Wp123*'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wp'
      MYSQL_PASSWORD: 'Wp123*'
    volumes:
      - mysql-data:/var/lib/mysql  
volumes:
  grafana_data:
  wordpress:
  mysql-data: