global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
  - targets: ['go-application:5000','python-application:5000','dotnet-application:5000','nodejs-application:5000']


- job_name: "WordPress metrics"
  static_configs:
    - targets: ['wordpress:80']
  metrics_path: '/index.php'
  params:
    rest_route: ['/metrics']
    all: ['yes']
    prometheus: ['fg98dfgkj']
  scheme: "http"