FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY src/work.csproj work/
RUN dotnet restore work/work.csproj
COPY src/ work/
WORKDIR /src/work
RUN dotnet build work.csproj --no-restore -c Release -o /app

FROM build AS publish
RUN dotnet publish work.csproj --no-restore -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "work.dll"]
