FROM golang:1.22.5 AS build

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o serv

FROM gcr.io/distroless/static-debian12:latest-amd64

COPY --from=build /app/serv .

EXPOSE 5000

CMD ["./serv"]
